#!/bin/bash

BUILTIN_RES='1920x1200' #native, but too small
BUILTIN_RES='1440x900'

reload-awesome () {
    echo 'awesome.restart()' | awesome-client
}

get-ext-dev () {
    xrandr | egrep '(^DP|HDMI).* connected' | cut -d' ' -f1
}

get-builtin-dev () {
    xrandr | egrep '(^eDP).* connected' | cut -d' ' -f1
}

builtin-on () {
    xrandr --output $(get-builtin-dev) --mode $BUILTIN_RES
}

builtin-off () {
    xrandr --output $(get-builtin-dev) --off
}

external-on () {
    xrandr --output $(get-ext-dev) --auto
}

external-off () {
    xrandr --output $(get-ext-dev) --off
}

external-on-builtin-off () {
    [[ ! -z "$(get-ext-dev)" ]] && external-on && builtin-off && reload-awesome
}

external-off-bulitin-on () {
    builtin-on && external-off && reload-awesome
}

case $1 in
    external) external-on; exit;;
    e) external-on; exit;;
    don) external-on-builtin-off exit;;
    doff) external-off-bulitin-on exit;;
    integrated) builtin-on; exit;;
    i) builtin-on; exit;;
    b) builtin-on; exit;;
    d) builtin-on; exit;;
esac
