#!/usr/bin/env bash

what=$(whiptail --menu 'What REPL?' 22 58 16 \
"lua" "lua" \
"haskell" "haskell" \
"ruby" "ruby" \
"perl" "perl" \
"python" "python" \
"js" "js" \
3>&1 1>&2 2>&3)

case $what
 in
    python)      ipython;;
    lua)         lua -i;;
    ruby)        irb;;
    js)          node;;
    perl)        perl -d -e 1;;
    haskell)     ghci;;
    *)           echo You did not choose any item;;
esac
