#!/bin/bash

echo '' > ~/.xsession-errors 

xmodmap -e "keycode 107 = Menu"
# caps -> ctrl
setxkbmap us -option caps:ctrl_modifier

#turnoff screensaver & dpms
xset -dpms s off
xset s off
xset s noblank
#keyb repeat
xset r rate 350 55

# see grep autorun ~/.config/awesome/rc.lua -A10
cowsay 'ssh passphrase:'
# agent is run via user systemd unit
ssh-add ~/.ssh/id_ed25519 ~/.ssh/id_rsa

cowsay 'root passwd:'

cd /tmp
su -
