#!/usr/bin/python3

import argparse
import subprocess
import sys

parser = argparse.ArgumentParser(description='Toasts a naughty message')
parser.add_argument('message', type=str, nargs='+', help='message words')
parser.add_argument('-t', '--title', nargs='*', help='title')
parser.add_argument('--timeout', type=int, default=0, help="timeout (secs), 0 = don't hide")
parser.add_argument('-p', '--preset', choices=('low', 'normal', 'critical'), default='normal', help="preset")
parser.add_argument('--fg', help='fg color')
parser.add_argument('--bg', help='bg color')


args = vars(parser.parse_args())
message = " ".join(args.pop("message"))
title = " ".join(args["title"]) if args["title"] else None
cmd = [
    "notify-send",
    "--app-name=toast",
    f'--urgency={args["preset"]}',
    f'--expire-time={args["timeout"] * 1000}',
]

if args['fg']:
    cmd += ["--hint", f'string:fgcolor:{args["fg"]}']
if args['bg']:
    cmd += ["--hint", f'string:bgcolor:{args["bg"]}']

if title:
    cmd += [title, message]
else:
    cmd.append(message)

try:
    result = subprocess.run(cmd, text=True, capture_output=True, timeout=5)
except subprocess.TimeoutExpired:
    sys.stderr.write("notify-send timed out; is a notification daemon running?\n")
    sys.exit(1)

sys.stdout.write(result.stdout)
sys.stderr.write(result.stderr)
sys.exit(result.returncode)
