#!/usr/bin/python3

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Toasts a naughty message')
parser.add_argument('message', type=str, nargs='+', help='message words')
parser.add_argument('-t', '--title', nargs='*', help='title')
parser.add_argument('--timeout', type=int, default=0, help="timout (secs), 0 = don't hide")
parser.add_argument('-p', '--preset', choices=('low', 'normal', 'critical'), default='normal', help="preset")
parser.add_argument('--fg', help='fg color')
parser.add_argument('--bg', help='bg color')

args = vars(parser.parse_args())
payload = ['text="%s"' % ' '.join(args.pop('message')),
           'timeout=%d' % args['timeout'],
           'preset=naughty.config.presets.%s' % args['preset']]

if args['title']:
    payload.append('title="%s"' % ' '.join(args['title']))
if args['fg']:
    payload.append('fg="%s"' % ' '.join(args['fg']))
if args['bg']:
    payload.append('bg="%s"' % ' '.join(args['bg']))

cmd = "echo 'local naughty=require(\"naughty\"); naughty.notify({%s})' | awesome-client" % ','.join(payload)

ps = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
ps.communicate()[0]
